# Generated by Django 5.0.3 on 2024-03-04 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_name', models.CharField(max_length=25)),
                ('cuisine_desc', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('price_point', models.IntegerField(blank=True)),
                ('address1', models.CharField(blank=True, max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50)),
                ('address3', models.CharField(blank=True, max_length=50)),
                ('address_city', models.CharField(blank=True, max_length=50)),
                ('address_state', models.CharField(blank=True, max_length=50)),
                ('address_zipcode', models.CharField(blank=True, max_length=9)),
                ('tel_number', models.CharField(blank=True, max_length=25)),
                ('email_addr', models.CharField(blank=True, max_length=50)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants')),
                ('image_url', models.URLField(blank=True)),
                ('cuisine', models.ManyToManyField(blank=True, related_name='cuisines', to='places.cuisine')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.cuisine')),
            ],
        ),
    ]
